### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by jim-rosales** [ShaynaCornelius/TeaCozy#6]
Since both these selectors apply the same styles you could have also done the following:

```CSS
.location h4,
.location h3 {
  padding-bottom: 10px;
}
```

https://github.com/ShaynaCornelius/TeaCozy/blob/9a08aa4e8e8bf2b1da572993ef40cbaabece8c65/resources/css/style.css#L162-L168
